/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OriginRouteImport } from './routes/origin'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SessionCompleteRouteImport } from './routes/session-complete'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TheBeginningRouteImport } from './routes/the-beginning'
import { Route as VedicScienceRouteImport } from './routes/vedic-science'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProgramProgramIdRouteImport } from './routes/program.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginRoute = OriginRouteImport.update({
  id: '/origin',
  path: '/origin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCompleteRoute = SessionCompleteRouteImport.update({
  id: '/session-complete',
  path: '/session-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TheBeginningRoute = TheBeginningRouteImport.update({
  id: '/the-beginning',
  path: '/the-beginning',
  getParentRoute: () => rootRouteImport,
} as any)
const VedicScienceRoute = VedicScienceRouteImport.update({
  id: '/vedic-science',
  path: '/vedic-science',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramProgramIdRoute = ProgramProgramIdRouteImport.update({
  id: '/program/$programId',
  path: '/program/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/origin': typeof OriginRoute
  '/player': typeof PlayerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/origin': typeof OriginRoute
  '/player': typeof PlayerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/delete-account': typeof DeleteAccountRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/origin': typeof OriginRoute
  '/player': typeof PlayerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/delete-account'
    | '/discover'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/origin'
    | '/player'
    | '/privacy'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/terms'
    | '/the-beginning'
    | '/vedic-science'
    | '/verify-email'
    | '/program/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/delete-account'
    | '/discover'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/origin'
    | '/player'
    | '/privacy'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/terms'
    | '/the-beginning'
    | '/vedic-science'
    | '/verify-email'
    | '/program/$programId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/delete-account'
    | '/discover'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/origin'
    | '/player'
    | '/privacy'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/terms'
    | '/the-beginning'
    | '/vedic-science'
    | '/verify-email'
    | '/program/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CategoryRoute: typeof CategoryRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  InspirationRoute: typeof InspirationRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OriginRoute: typeof OriginRoute
  PlayerRoute: typeof PlayerRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  RecentRoute: typeof RecentRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SessionCompleteRoute: typeof SessionCompleteRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TheBeginningRoute: typeof TheBeginningRoute
  VedicScienceRoute: typeof VedicScienceRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ProgramProgramIdRoute: typeof ProgramProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origin': {
      id: '/origin'
      path: '/origin'
      fullPath: '/origin'
      preLoaderRoute: typeof OriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-complete': {
      id: '/session-complete'
      path: '/session-complete'
      fullPath: '/session-complete'
      preLoaderRoute: typeof SessionCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-beginning': {
      id: '/the-beginning'
      path: '/the-beginning'
      fullPath: '/the-beginning'
      preLoaderRoute: typeof TheBeginningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedic-science': {
      id: '/vedic-science'
      path: '/vedic-science'
      fullPath: '/vedic-science'
      preLoaderRoute: typeof VedicScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$programId': {
      id: '/program/$programId'
      path: '/program/$programId'
      fullPath: '/program/$programId'
      preLoaderRoute: typeof ProgramProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CategoryRoute: CategoryRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  InspirationRoute: InspirationRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OriginRoute: OriginRoute,
  PlayerRoute: PlayerRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRoute,
  RecentRoute: RecentRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SessionCompleteRoute: SessionCompleteRoute,
  SubscriptionRoute: SubscriptionRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TheBeginningRoute: TheBeginningRoute,
  VedicScienceRoute: VedicScienceRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ProgramProgramIdRoute: ProgramProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
