/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SessionCompleteRouteImport } from './routes/session-complete'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TheBeginningRouteImport } from './routes/the-beginning'
import { Route as VedicScienceRouteImport } from './routes/vedic-science'
import { Route as ProgramProgramIdRouteImport } from './routes/program.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCompleteRoute = SessionCompleteRouteImport.update({
  id: '/session-complete',
  path: '/session-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TheBeginningRoute = TheBeginningRouteImport.update({
  id: '/the-beginning',
  path: '/the-beginning',
  getParentRoute: () => rootRouteImport,
} as any)
const VedicScienceRoute = VedicScienceRouteImport.update({
  id: '/vedic-science',
  path: '/vedic-science',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramProgramIdRoute = ProgramProgramIdRouteImport.update({
  id: '/program/$programId',
  path: '/program/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recent': typeof RecentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/session-complete': typeof SessionCompleteRoute
  '/subscription': typeof SubscriptionRoute
  '/team': typeof TeamRoute
  '/the-beginning': typeof TheBeginningRoute
  '/vedic-science': typeof VedicScienceRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/favorites'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/the-beginning'
    | '/vedic-science'
    | '/program/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/favorites'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/the-beginning'
    | '/vedic-science'
    | '/program/$programId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/category'
    | '/favorites'
    | '/home'
    | '/inspiration'
    | '/journey'
    | '/login'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/programs'
    | '/recent'
    | '/register'
    | '/search'
    | '/session-complete'
    | '/subscription'
    | '/team'
    | '/the-beginning'
    | '/vedic-science'
    | '/program/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CategoryRoute: typeof CategoryRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  InspirationRoute: typeof InspirationRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  RecentRoute: typeof RecentRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SessionCompleteRoute: typeof SessionCompleteRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TeamRoute: typeof TeamRoute
  TheBeginningRoute: typeof TheBeginningRoute
  VedicScienceRoute: typeof VedicScienceRoute
  ProgramProgramIdRoute: typeof ProgramProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-complete': {
      id: '/session-complete'
      path: '/session-complete'
      fullPath: '/session-complete'
      preLoaderRoute: typeof SessionCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-beginning': {
      id: '/the-beginning'
      path: '/the-beginning'
      fullPath: '/the-beginning'
      preLoaderRoute: typeof TheBeginningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedic-science': {
      id: '/vedic-science'
      path: '/vedic-science'
      fullPath: '/vedic-science'
      preLoaderRoute: typeof VedicScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$programId': {
      id: '/program/$programId'
      path: '/program/$programId'
      fullPath: '/program/$programId'
      preLoaderRoute: typeof ProgramProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CategoryRoute: CategoryRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  InspirationRoute: InspirationRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRoute,
  RecentRoute: RecentRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SessionCompleteRoute: SessionCompleteRoute,
  SubscriptionRoute: SubscriptionRoute,
  TeamRoute: TeamRoute,
  TheBeginningRoute: TheBeginningRoute,
  VedicScienceRoute: VedicScienceRoute,
  ProgramProgramIdRoute: ProgramProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
