// ─────────────────────────────────────────────────────────────
// Surawali Catalog Presets & Smart Template Matcher
// Authoritative Surawalis, Corporate Ragas, Ailment Mappings & Timings
// Enables one-click auto-population & smart upload mapping in Admin Console
// ─────────────────────────────────────────────────────────────

export interface SurawaliPreset {
  id: string;
  name: string;
  canonicalKey: string;
  subtitle: string;
  description: string;
  category: "devotional" | "secular" | "pregnancy";
  tier: "free" | "premium";
  artist: string;
  language: string;
  mappedAilments: string[];
  mappedTimings: string[];
  suggestedTags: string[];
  fallbackSongId: string;
  fallbackSongTitle: string;
  type: "core" | "corporate";
}

export const SURAWALI_PRESETS: SurawaliPreset[] = [
  {
    id: "sur_f3dd2f85-31bb-5c88-894f-fe06cc48e1d8",
    name: "Aagman",
    canonicalKey: "aagman",
    subtitle: "Garbha Sanskar — 9th Month Maternal Preparation",
    description: "Vedic harmonic composition specifically calibrated for the 9th month of pregnancy to foster maternal calm, harmonic vitality, and auspicious labor preparedness.",
    category: "pregnancy",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["9th Month Garbha Sanskar", "Maternal Relaxation", "Auspicious Delivery"],
    mappedTimings: ["6 to 8 pm"],
    suggestedTags: ["Meditation", "Healing", "Calm Mind"],
    fallbackSongId: "em_song_001",
    fallbackSongTitle: "Together We Make an Offering",
    type: "core",
  },
  {
    id: "sur_d9f95afe-21e3-5111-b49b-91832864adf6",
    name: "Anand mohini",
    canonicalKey: "anand mohini",
    subtitle: "Raga Chikitsa for Neuromuscular Relaxation & Joy",
    description: "Harmonic therapeutic scale designed to alleviate physical body pain, elevate mood into joyful clarity (Ananda), and provide deep neuromuscular relief.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Body pain", "Happy mood", "Paralysis"],
    mappedTimings: ["4 to 6 am", "any time"],
    suggestedTags: ["Mood Balance", "Energy", "Healing"],
    fallbackSongId: "em_song_002",
    fallbackSongTitle: "Divine Treasure",
    type: "core",
  },
  {
    id: "sur_ea0b7b64-b39b-5259-ab03-10c7c564e9a0",
    name: "Bhaas Haari",
    canonicalKey: "bhaas haari",
    subtitle: "Psychic Clarity & Sensory Stabilization",
    description: "A profound sonic therapy formulated to dispel sensory distortions, delusions, drowsiness, and mental agitation while restoring emotional grounding.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Delusions", "Drowsiness", "Hallucination", "Happy mood", "Schizophrenia"],
    mappedTimings: ["any time"],
    suggestedTags: ["Calm Mind", "Meditation", "Healing"],
    fallbackSongId: "em_song_003",
    fallbackSongTitle: "Hare Krishna Mantra – Raga Shiva Ranjani",
    type: "core",
  },
  {
    id: "sur_392d7dac-8c52-52bf-b62b-cd4f9612600f",
    name: "Dwaimadhyam",
    canonicalKey: "dwaimadhyam",
    subtitle: "Garbha Sanskar — 4th Month Heart & Organ Development",
    description: "Prescribed 4th-month prenatal raga formulation supporting fetal heart resonance, emotional serenity, and rhythmic cellular harmony.",
    category: "pregnancy",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["4th Month Garbha Sanskar", "Fetal Heart Balance"],
    mappedTimings: ["after lunch"],
    suggestedTags: ["Meditation", "Healing"],
    fallbackSongId: "em_song_004",
    fallbackSongTitle: "Vibhavari Sesa",
    type: "core",
  },
  {
    id: "sur_b719ad07-c4a5-51db-aaa5-48027611b68d",
    name: "Greeshma",
    canonicalKey: "greeshma",
    subtitle: "Pitta Thermal Cooling & Gastrointestinal Balance",
    description: "Vedic thermal-pacifying raga chikitsa that alleviates internal acidity, emotional anxiety, stress, metabolic imbalance, and neurological tremors.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: [
      "Acidity and vomitting",
      "Amnesia",
      "Anxiety and fear",
      "Cancer",
      "Hunger",
      "Indigestion",
      "Obesity",
      "Parkinson's",
      "Prostate enlargement",
      "Skin irritation",
      "Willingness",
    ],
    mappedTimings: ["before lunch", "after lunch", "6 to 8 am", "any time"],
    suggestedTags: ["Stress Relief", "Anxiety", "Healing", "Calm Mind"],
    fallbackSongId: "em_song_005",
    fallbackSongTitle: "Jaya Radha-Madhava",
    type: "core",
  },
  {
    id: "sur_d7c98509-a2b1-5392-8a2a-9daba9a37457",
    name: "Jwarankush",
    canonicalKey: "jwarankush",
    subtitle: "Thermal Fever Control & Cellular Purification",
    description: "Ancient remedial raga calibrated to cool excess bodily fire (Pitta), reduce feverish temperature, and soothe internal skin inflammation.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Control of fever", "Skin diseases due to internal heat"],
    mappedTimings: ["any time"],
    suggestedTags: ["Healing", "Calm Mind"],
    fallbackSongId: "em_song_006",
    fallbackSongTitle: "I Trust You",
    type: "core",
  },
  {
    id: "sur_b5cd60d9-312a-5aa3-96ba-eb6f0217d7c0",
    name: "Karnawati",
    canonicalKey: "karnawati",
    subtitle: "Auditory & Sensory Nerve Regulation (7th Month Care)",
    description: "Targeted auditory therapy supporting sensory nerve integration, hearing acuity, cognitive focus in children, and 7th-month prenatal resonance.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Autism", "Hearing impairment", "Regulate functions of sensory organs", "7th Month Garbha Sanskar"],
    mappedTimings: ["any time"],
    suggestedTags: ["Focus", "Healing", "Meditation"],
    fallbackSongId: "em_song_007",
    fallbackSongTitle: "Hare Krishna Vraja Mahamantra 4",
    type: "core",
  },
  {
    id: "sur_94a123c7-161a-5293-9379-36f72f77495c",
    name: "Madhuparna",
    canonicalKey: "madhuparna",
    subtitle: "Metabolic Harmony & Endocrine Regulation",
    description: "Calibrated raga therapy designed to stimulate balanced pancreatic and vascular functions for managing diabetes, glucose levels, and blood pressure.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Diabetes", "Hypertension"],
    mappedTimings: ["any time"],
    suggestedTags: ["Healing", "Mood Balance"],
    fallbackSongId: "em_song_008",
    fallbackSongTitle: "Mayapur Meltdown – Maha Sankirtan",
    type: "core",
  },
  {
    id: "sur_9beaed13-bd4a-5c3a-b3bc-3461b1d5e91c",
    name: "Marut",
    canonicalKey: "marut",
    subtitle: "Vata Air-Flow Balancing for Joints & Spine",
    description: "Potent Vata-pacifying sound therapy that alleviates arthritis, lower back pain, sciatica, spinal stiffness, and vocal articulation blocks.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Arthritis", "Back pain", "Neck fixing", "Sciatica", "Speech impairment", "3rd Month Garbha Sanskar"],
    mappedTimings: ["5 to 7 am", "6 to 8 am", "any time"],
    suggestedTags: ["Healing", "Energy"],
    fallbackSongId: "em_song_009",
    fallbackSongTitle: "Searching for the Divine Love",
    type: "core",
  },
  {
    id: "sur_2eaaa7d7-a034-5c9a-8118-8ff0844985d6",
    name: "Nidra mohini",
    canonicalKey: "nidra mohini",
    subtitle: "Deep Delta Sleep, Serotonin & Migraine Relief",
    description: "Vedic nocturnal raga chikitsa specifically engineered to induce delta brainwave synchrony, soothe chronic insomnia, calm migraine throbbing, and uplift mood.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Addiction", "Depression", "Insomnia (sleeplessness)", "Migraine", "Satisfaction and happiness"],
    mappedTimings: ["before sleep", "any time"],
    suggestedTags: ["Sleep", "Stress Relief", "Calm Mind", "Healing"],
    fallbackSongId: "em_song_010",
    fallbackSongTitle: "Hare Krishna Mahamantra Version 14",
    type: "core",
  },
  {
    id: "sur_18c57c14-e5ec-5c3f-8b49-92054b343604",
    name: "Pad dukh harini",
    canonicalKey: "pad dukh harini",
    subtitle: "Lower Extremity & Joint Pain De-escalation",
    description: "Targeted acoustic therapy formulated to release muscular constriction and pain in the feet, ankles, and knee joints.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["foot pain", "Knee pain"],
    mappedTimings: ["4 to 6 am"],
    suggestedTags: ["Healing", "Calm Mind"],
    fallbackSongId: "em_song_011",
    fallbackSongTitle: "Jiv Jaago",
    type: "core",
  },
  {
    id: "sur_9c310173-44ef-552a-a3ce-7731928d8e99",
    name: "Parjanya",
    canonicalKey: "parjanya",
    subtitle: "Pranayama & Respiratory Airway Expansion",
    description: "Expansive harmonic frequency designed to soothe bronchial irritation, ease asthmatic wheezing, and regulate natural respiratory rhythms.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Asthma", "Respiratory problems"],
    mappedTimings: ["any time"],
    suggestedTags: ["Healing", "Energy", "Meditation"],
    fallbackSongId: "em_song_012",
    fallbackSongTitle: "Sri Krishna Divya Nam",
    type: "core",
  },
  {
    id: "sur_c63b8f7b-bc54-5fb5-877c-e5dd7be5b152",
    name: "Prabhaati",
    canonicalKey: "prabhaati",
    subtitle: "Morning Cortisol De-escalation & Mental Clarity",
    description: "Gentle morning raga sequence composed to reset autonomic nervous system tension, dissipate early cortisol spikes, and center morning focus.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Stress ralaxation (morning)", "Mental Clarity"],
    mappedTimings: ["6 to 9 am"],
    suggestedTags: ["Stress Relief", "Focus", "Calm Mind"],
    fallbackSongId: "em_song_013",
    fallbackSongTitle: "Hare Krishna Mahamantra Version 17",
    type: "core",
  },
  {
    id: "sur_6aef70e8-79d0-58f3-bab8-4b869a91dcfe",
    name: "Prabhati",
    canonicalKey: "prabhati",
    subtitle: "Garbha Sanskar — 5th Month Sensory Activation",
    description: "Acoustic prenatal stimulation formulated for the 5th month of gestation to awaken sensory alertness and nurture fetal vitality.",
    category: "pregnancy",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["5th Month Garbha Sanskar", "Sensory Awakening"],
    mappedTimings: ["6 to 9 am"],
    suggestedTags: ["Meditation", "Healing"],
    fallbackSongId: "em_song_014",
    fallbackSongTitle: "Uplifting Hare Krishna Kirtan",
    type: "core",
  },
  {
    id: "sur_5a4381ec-99af-5af2-ab4b-9a4de85bab26",
    name: "Santul",
    canonicalKey: "santul",
    subtitle: "Tridoshic Systemic Balance & Cardiovascular Health",
    description: "Complete equilibrium raga (Sama-Dosha) formulated to regulate blood pressure, thyroid, digestion, and systemic metabolic balance.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: [
      "Constipation",
      "Dialysis",
      "Dry cough",
      "Dry Skin",
      "Hypertension",
      "Hypothyroid",
      "Kidney stone",
      "Tinitus",
      "Vericose veins",
      "Weight gain",
      "2nd Month Garbha Sanskar",
    ],
    mappedTimings: ["6 to 9 am", "6 to 9am", "any time"],
    suggestedTags: ["Healing", "Mood Balance", "Meditation"],
    fallbackSongId: "em_song_015",
    fallbackSongTitle: "Hare Krishna Mantra – Raga Desi",
    type: "core",
  },
  {
    id: "sur_25aba99d-1a06-5a82-99a7-f283f8d8b972",
    name: "Smrutigandha",
    canonicalKey: "smrutigandha",
    subtitle: "Cognitive Memory, Neuro-Plasticity & Dementia Care",
    description: "Neuro-regenerative sonic frequencies tailored to activate synaptic connection, support memory retention, and protect against Alzheimer's / cognitive decline.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Alziemer", "Dementia", "Impairment of sensory functions", "Memory loss"],
    mappedTimings: ["any time"],
    suggestedTags: ["Focus", "Healing", "Meditation"],
    fallbackSongId: "em_song_016",
    fallbackSongTitle: "A Prayer in the Ether",
    type: "core",
  },
  {
    id: "sur_66d06e8a-dd55-5339-956f-edb8211ca3fe",
    name: "Sthairya",
    canonicalKey: "sthairya",
    subtitle: "Equanimity, Ocular Health & 8th Month Prenatal Care",
    description: "Vedic grounding raga establishing deep psychological stability, cellular stillness (Sthairya), ocular eye health, and 8th-month fetal protection.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani",
    language: "hi",
    mappedAilments: ["Catract", "Stable mind", "8th Month Garbha Sanskar"],
    mappedTimings: ["8 to 10am", "any time"],
    suggestedTags: ["Calm Mind", "Meditation", "Healing"],
    fallbackSongId: "em_song_017",
    fallbackSongTitle: "Tava Kathamritam / Maha Mantra",
    type: "core",
  },

  // ── Corporate Wellness Ragas ──
  {
    id: "cr_afdc68b4-9331-4a70-8b80-3bf6b03e898f",
    name: "Hindol (Sunday Corporate)",
    canonicalKey: "hindol",
    subtitle: "Weekend Cognitive Refresh & Creative Renewal",
    description: "Vedic morning raga Hindol calibrated to dispel mental fatigue, invigorate workplace vitality, and awaken creative flow.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani Corporate",
    language: "hi",
    mappedAilments: ["Weekend Mental Reset", "Creative Awakening"],
    mappedTimings: ["6 am to 8 am at home or while travelling"],
    suggestedTags: ["Energy", "Focus", "Mood Balance"],
    fallbackSongId: "em_song_018",
    fallbackSongTitle: "Heart on Fire (Hari Hari Bifale)",
    type: "corporate",
  },
  {
    id: "cr_07ec9ec0-2f8b-4ff2-949f-04e4144e0b23",
    name: "Madhuprabhat (Monday Corporate)",
    canonicalKey: "madhuprabhat",
    subtitle: "Monday Focus & Workplace Stress Neutralization",
    description: "Specialized Monday morning auditory frequency to eliminate Monday morning inertia and prime executive decision-making clarity.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani Corporate",
    language: "hi",
    mappedAilments: ["Monday Stress", "Executive Focus"],
    mappedTimings: ["6 am to 8 am at home or while travelling"],
    suggestedTags: ["Focus", "Stress Relief"],
    fallbackSongId: "em_song_019",
    fallbackSongTitle: "Mellows of a Mendicant",
    type: "corporate",
  },
  {
    id: "cr_b82be30c-d89d-4799-bca8-acd4084bcdda",
    name: "Ahir Bhairav (Tuesday Corporate)",
    canonicalKey: "ahir bhairav",
    subtitle: "Midweek De-escalation & Mental Steadiness",
    description: "Deep morning grounding scale to sustain concentration during intense corporate demands and prevent cognitive burnout.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani Corporate",
    language: "hi",
    mappedAilments: ["Cognitive Stamina", "Burnout Prevention"],
    mappedTimings: ["6 am to 8 am at home or while travelling"],
    suggestedTags: ["Focus", "Calm Mind"],
    fallbackSongId: "em_song_020",
    fallbackSongTitle: "Queen Kunti",
    type: "corporate",
  },
  {
    id: "cr_24f15b13-ab22-4afe-8e30-3df071ed88d0",
    name: "Miyan kee Todi (Wednesday Corporate)",
    canonicalKey: "miyan kee todi",
    subtitle: "Wednesday Midweek Deep Centering",
    description: "Resonant classical raga composition suppressing mental scatteredness and elevating profound analytical focus.",
    category: "secular",
    tier: "free",
    artist: "Krishna Sanjeevani Corporate",
    language: "hi",
    mappedAilments: ["Analytical Focus", "Stress Dissipation"],
    mappedTimings: ["6 am to 8 am at home or while travelling"],
    suggestedTags: ["Focus", "Meditation"],
    fallbackSongId: "em_song_021",
    fallbackSongTitle: "Guha Maha Mantra",
    type: "corporate",
  },
];

/**
 * Smart filename matcher to automatically recognize a Surawali from an uploaded file name.
 * e.g. "Santul - Final Master.mp3" -> Matches Santul
 * e.g. "05_greeshma_432hz.wav" -> Matches Greeshma
 * e.g. "nidra_mohini.mp3" -> Matches Nidra mohini
 */
export function findSurawaliByFilename(filename: string): SurawaliPreset | null {
  if (!filename) return null;
  const clean = filename
    .toLowerCase()
    .replace(/\.[a-z0-9]+$/i, "") // remove extension
    .replace(/[_-]+/g, " ") // normalize separators to spaces
    .trim();

  // 1. Direct match on canonicalKey
  for (const preset of SURAWALI_PRESETS) {
    if (clean.includes(preset.canonicalKey) || preset.canonicalKey.includes(clean)) {
      return preset;
    }
  }

  // 2. Tokenized word matching
  const words = clean.split(/\s+/);
  for (const preset of SURAWALI_PRESETS) {
    const presetWords = preset.name.toLowerCase().split(/\s+/);
    if (presetWords.some(pw => pw.length > 3 && words.includes(pw))) {
      return preset;
    }
  }

  return null;
}
